# Simulation parameters
dt: 0.007
simulation_time: 150 # seconds
frame_skip: 16 # Number of frames to skip for smoother animation
threshold: 2.0  # Stop simulation if within 2 meters of final target
target_shift_threshold_distance: 5 # Shift to next segment if within 10 meters of current segment

max_rpm: 3000 # Maximum RPM for the motors
n_rotors: 4 # Number of rotors
max_roll_angle: 30
max_pitch_angle: 30
max_yaw_angle: 30 # Maximum yaw angle in degrees

max_h_speed_limit_kmh: 50.0
max_v_speed_limit_kmh: 20.0
max_angle_limit_deg: 30.0
anti_windup_contrib: 0.4

# Rotor model parameters
norm_params_path: "Rotor/normalization_params.pth"
rotor_model_path: "Rotor/rotor_model.pth"

# PID controller settings (yaw remain fixed)
k_pid_yaw: [0.5, 1e-6, 0.1]
k_pid_pos: [0.7, 0.01, 0.09]
k_pid_alt: [0.7, 0, 0.1]
k_pid_att: [20, 1, 0.01]
k_pid_hsp: [1, 0.01, 0.01]
k_pid_vsp: [150, 10, 1]


# Drone parameters
m: 5.2
I: [3.8e-3, 3.8e-3, 7.1e-3]
d: 7.5e-7
l: 0.32
Cd: [0.1, 0.1, 0.15]
Ca: [0.1, 0.1, 0.15]
Jr: 6e-5

# World settings
world_data_path: "Worlds/world_winterthur.pkl"

# Noise parameters
dnn_model_filename: "Noise/angles_swl.npy"
empa_model_filename: "Noise/model_coefficients.npz"
empa_model_scaling_filename: "Noise/scaler.joblib"
rpm_reference: 2500

